_ctp_example_index:
    path:     /
    defaults: { _controller: ExampleBundle:Home:index }

_ctp_example:
    path:     /product
    defaults: { _controller: ExampleBundle:Catalog:index }

_ctp_example_product:
    path:    /product/slug/{slug}
    defaults: { _controller: ExampleBundle:Catalog:detailBySlug }

_ctp_example_product_by_id:
    path:    /product/id/{id}
    defaults: { _controller: ExampleBundle:Catalog:detailById }

login:
    path: /login
    defaults: { _controller: ExampleBundle:User:login }
login_check:
    path: /login_check
    defaults: { _controller: ExampleBundle:User:login }
logout:
    path: /logout

_ctp_example_user_details:
    path:    /user/details
    defaults: { _controller: ExampleBundle:User:details }

_ctp_example_user_address_book:
    path:    /user/address
    defaults: { _controller: ExampleBundle:User:addressBook }

_ctp_example_user_address_edit:
    path:    /user/address/edit/{addressId}
    defaults: { _controller: ExampleBundle:User:editAddress }

_ctp_example_cart:
    path: /cart
    defaults: { _controller: ExampleBundle:Cart:index}

_ctp_example_checkout_signin:
    path: /checkout/signin
    defaults: { _controller: ExampleBundle:Checkout:signin}

_ctp_example_checkout_shipping:
    path: /checkout/shipping
    defaults: { _controller: ExampleBundle:Checkout:shippingMethod}

_ctp_example_checkout_address:
    path: /checkout/address
    defaults: { _controller: ExampleBundle:Checkout:setAddress}

_ctp_example_checkout_confirm:
    path: /checkout/address/confirm
    defaults: { _controller: ExampleBundle:Checkout:confirmation}

_ctp_example_add_lineItem:
    path: /cart/add
    defaults: { _controller: ExampleBundle:Cart:addLineItem}

_ctp_example_change_lineItem:
    path: /cart/change
    defaults: { _controller: ExampleBundle:Cart:changeLineItem}

_ctp_example_delete_lineItem:
    path: /cart/delete
    defaults: { _controller: ExampleBundle:Cart:deleteLineItem}

_ctp_example_checkout_guest:
    path: /checkout/quest
    defaults: { _controller: ExampleBundle:Checkout:setAddress}

_ctp_example_checkout_success:
    path: /checkout/succes
    defaults: { _controller: ExampleBundle:Checkout:success}

_ctp_example_orders_all:
    path: /orders/
    defaults: { _controller: ExampleBundle:Order:index}

_ctp_example_order:
    path: /orders/{orderId}
    defaults: { _controller: ExampleBundle:Order:showOrder}

_ctp_example_suggest:
    path: /suggest/{searchTerm}
    defaults: { _controller: ExampleBundle:Catalog:suggest}

_ctp_example_shopping_list:
    path: /shoppinglist
    defaults: { _controller: ExampleBundle:ShoppingList:index }

shopping_list_create:
    path: /shoppinglist/create
    defaults: { _controller: ExampleBundle:ShoppingList:create }

_ctp_example_add_lineItem_to_shoppingList:
    path: /shoppinglist/addlineitem
    defaults: { _controller: ExampleBundle:ShoppingList:addLineItem }

shopping_list_remove_line_item:
    path: /shoppinglist/removelineitem
    controller: App\Controller\ShoppingListController::removeLineItem
    methods: [POST]

shopping_list_change_line_item_quantity:
    path: /shoppinglist/changelineitemquantity
    controller: App\Controller\ShoppingListController::changeLineItemQuantity
    methods: [POST]
